FROM nvidia/cuda:13.0.0-devel-ubuntu24.04
ARG GROOT_REF=ead52833afbbf4243f8cd5e7664f48a94de03b19
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    cmake \
    git \
    sed \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y \
    python3.10 \
    python3.10-dev \
    python3.10-venv \
    && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
RUN python3.10 -m ensurepip --upgrade \
    && python3.10 -m pip install --upgrade pip setuptools wheel packaging ninja

RUN apt-get remove -y python3-cryptography python3-cryptography-dev 2>/dev/null || true
RUN python3 -m pip install --ignore-installed cryptography

RUN git clone https://github.com/NVIDIA/Isaac-GR00T.git /Isaac-GR00T
RUN cd /Isaac-GR00T && \
    git checkout "${GROOT_REF}" && \
    git rev-parse --verify HEAD && \
    sed -i '/flash-attn==/d' pyproject.toml && \
    python3 -m pip install -e . --break-system-packages
RUN cd /Isaac-GR00T/gr00t/eval/real_robot/SO100 && \
    python3 -m pip install -e . --break-system-packages
RUN python3 -m pip uninstall -y torch torchvision torchaudio && python3 -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130
RUN export MAX_JOBS=1 && python3 -m pip install flash-attn --no-build-isolation --no-cache-dir
RUN python3 -m pip install feetech-servo-sdk

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
COPY docker/utils.sh /root/tmp/utils.sh
RUN cat /root/tmp/utils.sh >> /root/.bashrc && rm /root/tmp/utils.sh

# for rerun GUI
RUN apt-get update && apt-get install -y \
    libx11-6 \
    libxcb1 \
    libxkbcommon0 \
    libxkbcommon-x11-0 \
    libgl1 \
    libegl1 \
    libxrandr2 \
    libxinerama1 \
    libxcursor1 \
    libxi6 \
    && rm -rf /var/lib/apt/lists/*
